// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9pZBR4V02e7PFRyyHicBdlRomTvX8Ir0',
    appId: '1:73475847078:web:36b7aef0d1b64078c8d567',
    messagingSenderId: '73475847078',
    projectId: 'flutter-app-5f3b4',
    authDomain: 'flutter-app-5f3b4.firebaseapp.com',
    databaseURL: 'https://flutter-app-5f3b4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-5f3b4.firebasestorage.app',
    measurementId: 'G-MX23D9XQ8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOdunlnc4eMMHVItVUfQdAau7zWiozyLE',
    appId: '1:73475847078:android:322cae1797033440c8d567',
    messagingSenderId: '73475847078',
    projectId: 'flutter-app-5f3b4',
    databaseURL: 'https://flutter-app-5f3b4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-5f3b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV1BTDGUoKuyAPLIGVwUfgCwWzSR0gbmY',
    appId: '1:73475847078:ios:3f8b3f2f22c1a41cc8d567',
    messagingSenderId: '73475847078',
    projectId: 'flutter-app-5f3b4',
    databaseURL: 'https://flutter-app-5f3b4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-5f3b4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV1BTDGUoKuyAPLIGVwUfgCwWzSR0gbmY',
    appId: '1:73475847078:ios:3f8b3f2f22c1a41cc8d567',
    messagingSenderId: '73475847078',
    projectId: 'flutter-app-5f3b4',
    databaseURL: 'https://flutter-app-5f3b4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-5f3b4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9pZBR4V02e7PFRyyHicBdlRomTvX8Ir0',
    appId: '1:73475847078:web:132b9311349d98bcc8d567',
    messagingSenderId: '73475847078',
    projectId: 'flutter-app-5f3b4',
    authDomain: 'flutter-app-5f3b4.firebaseapp.com',
    databaseURL: 'https://flutter-app-5f3b4-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-5f3b4.firebasestorage.app',
    measurementId: 'G-XDVD66NWDY',
  );
}
